public class DiffBtw2Str389 {
    /*
389. Find the Difference
Easy

596

251

Favorite

Share
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/
    public static void main(String[] args) {
        System.out.println(findTheDifference1("abcd","abfcd"));
        int prod = 1,sum = 0;
        int n=123;
        while(n!= 0){
            prod *=n%10;
            sum  +=n%10;
            n/=10;
        }
        System.out.println((prod - sum));
    }

    public static char findTheDifference(String s, String t) {
        int[] arr = new int[26];
        for (char c : s.toCharArray()) {
            arr[c - 'a']++;
        }
        for (char c : t.toCharArray()) {
            if (arr[c - 'a']-- == 0)
                return c;
        }
        return ' ';
    }
    public static char findTheDifference1(String s, String t) {
        int n = t.length();
        char c = t.charAt(n - 1);
        for (int i = 0; i < n - 1; ++i) {
            System.out.println("xor ing "+c + " with "+s.charAt(i));
            c ^= s.charAt(i);
            System.out.println("result c = "+c);
            System.out.println("xor ing "+c + " with "+t.charAt(i));
            c ^= t.charAt(i);
            System.out.println("result c = "+c);
        }
        return c;
    }
    public static char findTheDifference2(String s, String t) {
        char[] chs = s.toCharArray(), cht = t.toCharArray();
        int sums = 0, sumt = 0;
        for(char c : chs)
            sums += (int)c;
        for(char c : cht)
            sumt += (int)c;
        return (char)(sumt-sums);
    }


}
